/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package core;

import util.StringUtils;

public class Utils {

    public static boolean isAllPositiveNumbers(String... strings) {
        for (String str : strings) {
            if (!StringUtils.isPositiveNumber(str)) {
                return false;
            }
        }
        return true;
    }
}
