/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi;

import util.Utils;

public class App {

    public static void main(String[] args) {
        boolean isAllPositive = Utils.isAllPositiveNumbers("12", "79");
        System.out.println(isAllPositive);
    }
}
